### ISSUE TITLE
The backupPlanRef of the backup job is lost during pressure measurement

### ISSUE THREAD

**Issue by fuchunlan** [jibutech/backup-saas-client#75] opened 2021-12-13 04:36 UTC
![image](https://user-images.githubusercontent.com/63338728/145753171-cdc964ac-4b2f-487c-b357-37b43bb0e6f6.png)

**Comment by shaofeng66** [comment] 2021-12-15 03:25
The root cause is the backupPlanRef is set by saas server, however in repeat plan, the job is generated from backend CR, this field is not set.
https://github.com/jibutech/backup-saas-for-kubesphere-cloud/blob/main/pkg/models/backupplan/backupplan.go#L245

Similarly the SubmitTime
https://github.com/jibudata/tenant-operator/blob/main/controllers/backupjob_controller.go#L383

Need to make sure any other field that set by rest server is also properly handled.

**Comment by jerry-jibu** [comment] 2021-12-21 01:32
fix is done by @shaofeng66  and will be released in this week.

**Comment by shaofeng66** [comment] 2021-12-22 07:14
fixed in saas release 20211222

**Closed** 2021-12-22 09:16 UTC
